#! /usr/bin/env bash

mkdir -p ~/.ssh/
ssh-keygen -f ~/.ssh/ids_rsa -q -N ""
echo "Key copied to clipboard!"
cat ~/.ssh/ids_rsa.pub | xclip -selection c
echo "Key should appear here:"
echo $(ssh-add -l)

read -p "Press enter to continue"
echo "Cloning provision"

nix-shell -p git --command "git clone git@github.com:bbtdev/provision.git $HOME/.provision"
